In [1]:
import pandas as pd 
import os 
import numpy as np 
os.chdir(r"H:\Bulk_medulloblastoma_A_to_I_editing_finalized\ICGC_Only_Analysis\data\genome_information")

In [13]:
gene_information = pd.read_csv("ICGC_genome_information.csv", index_col=0)

In [15]:
Exon = gene_information[gene_information['Func.ensGene'] == 'exonic']

In [22]:
Exon_NS = Exon[Exon['ExonicFunc.ensGene'] == "nonsynonymous SNV"]

In [33]:
Exon_NS_polyphen = Exon_NS[['Gene.ensGene','Polyphen2_HDIV_score', 'Polyphen2_HDIV_pred', 'Polyphen2_HVAR_score','Polyphen2_HVAR_pred']]
Exon_NS_polyphen.sort_values(by="Polyphen2_HDIV_score",ascending=False, inplace=True)

C:\Users\17867\AppData\Local\Temp\ipykernel_6268\3031184097.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Exon_NS_polyphen.sort_values(by="Polyphen2_HDIV_score",ascending=False, inplace=True)

In [36]:
Exon_NS_polyphen[
    (Exon_NS_polyphen['Polyphen2_HDIV_pred'] == 'D') &
    (Exon_NS_polyphen['Polyphen2_HVAR_pred'] == 'D')
]

,Gene.ensGene,Polyphen2_HDIV_score,Polyphen2_HDIV_pred,Polyphen2_HVAR_score,Polyphen2_HVAR_pred
chr16_58040072,MMP15,1.0,D,0.999,D
chr9_21815441,MTAP;RP11-145E5.5,1.0,D,1.0,D
chr4_57010413,POLR2B,1.0,D,0.999,D
chr19_38632628,EIF3K,1.0,D,0.999,D
chr9_5069137,JAK2,1.0,D,0.991,D
chr19_37363201,HKR1,1.0,D,0.998,D
chr5_141393931,PCDHGA8,1.0,D,1.0,D
chr19_57685341,ZNF551,1.0,D,1.0,D
chrX_41343328,DDX3X,1.0,D,0.999,D
chrX_41346514,DDX3X,1.0,D,0.993,D
chr12_62393091,USP15,1.0,D,0.999,D
chr6_144436020,UTRN,1.0,D,1.0,D
chr18_8718479,MTCL1,1.0,D,0.999,D
chr18_74634128,ZNF407,1.0,D,0.993,D
chr18_35246147,ZNF397,1.0,D,1.0,D
chr18_53410569,DCC,1.0,D,1.0,D
chr4_61998230,ADGRL3,0.999,D,0.996,D
chr7_92450717,GATAD1,0.999,D,0.986,D
chr17_28693823,SUPT6H,0.999,D,0.936,D
chr1_223003150,DISP1,0.999,D,0.988,D
chr16_89854542,SPIRE2,0.999,D,0.973,D
chr11_993849,AP2A2,0.999,D,0.985,D
chr2_85028035,KCMF1,0.999,D,0.986,D
chr1_46035138,MAST2,0.999,D,0.986,D
chr4_41598921,LIMCH1,0.998,D,0.995,D
chr18_74633189,ZNF407,0.998,D,0.939,D
chr22_29214928,EMID1,0.998,D,0.987,D
chr11_67609595,NDUFV1,0.998,D,0.981,D
chr19_36877596,ZNF345,0.998,D,0.918,D
chr9_93292780,WNK2,0.998,D,0.992,D
chr15_59031633,RNF111,0.998,D,0.994,D
chr3_179375226,MFN1,0.998,D,0.99,D
chr2_189007561,COL3A1,0.997,D,0.996,D
chr2_189474726,WDR75,0.997,D,0.932,D
chr13_32770364,PDS5B,0.997,D,0.993,D
chr19_11021836,SMARCA4,0.997,D,0.976,D
chr20_33640512,CBFA2T2,0.996,D,0.951,D
chr5_171183192,RANBP17,0.996,D,0.937,D
chr3_62438132,CADPS,0.996,D,0.951,D
chr6_52403805,PAQR8,0.995,D,0.976,D
chr17_49791913,KAT7,0.994,D,0.97,D
chr4_1974938,NSD2,0.994,D,0.986,D
chr4_166091153,TLL1,0.994,D,0.988,D
chr1_228489051,RNF187,0.993,D,0.968,D
chr8_60781381,CHD7,0.993,D,0.971,D
chr8_17956605,PCM1,0.992,D,0.984,D
chr19_5653419,SAFB,0.992,D,0.973,D
chr14_67110222,GPHN,0.991,D,0.976,D
chrX_51895131,MAGED1,0.984,D,0.956,D
chr3_23889173,UBE2E1,0.984,D,0.958,D
chr7_74733937,GTF2I,0.982,D,0.952,D
chr17_66803964,PRKCA,0.982,D,0.917,D
chr16_2933944,FLYWCH1,0.981,D,0.954,D
chrX_51896845,MAGED1,0.98,D,0.977,D
chr1_1336513,DVL1,0.974,D,0.969,D
chr1_26766297,ARID1A,0.969,D,0.914,D

In [30]:
Exon_NS.sort_values(by="Polyphen2_HDIV_score",ascending=False)

,Chr,Start,End,Ref,Alt,Func.ensGene,Gene.ensGene,GeneDetail.ensGene,ExonicFunc.ensGene,AAChange.ensGene,...,gnomad41_genome_AF_ami,gnomad41_genome_AF_amr,gnomad41_genome_AF_asj,gnomad41_genome_AF_eas,gnomad41_genome_AF_fin,gnomad41_genome_AF_mid,gnomad41_genome_AF_nfe,gnomad41_genome_AF_remaining,gnomad41_genome_AF_sas,Otherinfo1
chr16_58040072,chr16,58040072,58040072,A,G,exonic,MMP15,NaN,nonsynonymous SNV,MMP15:ENST00000219271.3:exon4:c.A638G:p.D213G,...,.,.,.,.,.,.,.,.,.,+
chr9_21815441,chr9,21815441,21815441,A,G,exonic,MTAP;RP11-145E5.5,NaN,nonsynonymous SNV,"MTAP:ENST00000380172.8:exon2:c.A42G:p.I14M,RP1...",...,.,.,.,.,.,.,.,.,.,+
chr4_57010413,chr4,57010413,57010413,A,G,exonic,POLR2B,NaN,nonsynonymous SNV,POLR2B:ENST00000639658.1:exon9:c.A1232G:p.N411...,...,.,.,.,.,.,.,.,.,.,+
chr19_38632628,chr19,38632628,38632628,A,G,exonic,EIF3K,NaN,nonsynonymous SNV,"EIF3K:ENST00000538434.5:exon5:c.A188G:p.Y63C,E...",...,.,.,.,.,.,.,.,.,.,+
chr9_5069137,chr9,5069137,5069137,A,G,exonic,JAK2,NaN,nonsynonymous SNV,JAK2:ENST00000381652.3:exon11:c.A1442G:p.Y481C,...,.,.,.,.,.,.,.,.,.,+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
chr1_26448387,chr1,26448387,26448387,A,G,exonic,DHDDS,NaN,nonsynonymous SNV,DHDDS:ENST00000427245.6:exon7:c.A574G:p.S192G,...,0,0,0,0,0,0,0,0,0,+
chr12_11034803,chr12,11034803,11034803,T,C,exonic,PRH1-PRR4,NaN,nonsynonymous SNV,PRH1-PRR4:ENST00000536668.2:exon3:c.A88G:p.T30A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-
chr7_142715788,chr7,142715788,142715788,A,G,exonic,TRBV27,NaN,nonsynonymous SNV,TRBV27:ENST00000390399.3:exon2:c.A271G:p.R91G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,+
chr7_142715840,chr7,142715840,142715840,A,G,exonic,TRBV27,NaN,nonsynonymous SNV,TRBV27:ENST00000390399.3:exon2:c.A323G:p.Y108C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,+
chr7_142715854,chr7,142715854,142715854,A,G,exonic,TRBV27,NaN,nonsynonymous SNV,TRBV27:ENST00000390399.3:exon2:c.A337G:p.S113G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,+

In [ ]:
.['Polyphen2_HDIV_pred'].value_counts()

Polyphen2_HDIV_pred
B    197
.     81
D     72
P     56
Name: count, dtype: int64

In [25]:
Exon_NS['Polyphen2_HVAR_pred'].value_counts()

Polyphen2_HVAR_pred
B    229
.     81
D     58
P     38
Name: count, dtype: int64

In [11]:
Exon.columns[Exon.columns.str.contains("Poly")]

Index(['Polyphen2_HDIV_score', 'Polyphen2_HDIV_pred', 'Polyphen2_HVAR_score',
       'Polyphen2_HVAR_pred'],
      dtype='object')